Tasks 1, 3, 6, 7, 8, 9, 45 and 58.

# 1
Import the numpy package under the name np

In [1]:
import numpy as np

# 3
Create a null vector of size 10

In [5]:
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# 6
Create a null vector of size 10 but the fifth value which is 1

In [6]:
null_vector = np.zeros(10)
null_vector[4] = 1
null_vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

# 7
Create a vector with values ranging from 10 to 49

In [10]:
f_10_to_49 = np.arange(10, 50, 1)
f_10_to_49

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

# 8
Reverse a vector (first element becomes last) 

In [17]:
f_10_to_49 = f_10_to_49[::-1]
f_10_to_49

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

# 9
Create a 3x3 matrix with values ranging from 0 to 8

In [30]:
t_t_matrix = np.arange(0, 9)
t_t_matrix = t_t_matrix.reshape(3,-1)
t_t_matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# 45
Create random vector of size 10 and replace the maximum value by 0

In [40]:
random_vetor = np.random.random(10)
random_vetor[random_vetor.argmax()] = 0
random_vetor

array([0.87044393, 0.60140216, 0.58978743, 0.16365987, 0.2718822 ,
       0.63919629, 0.        , 0.69105327, 0.57305271, 0.50452892])

# 58
Subtract the mean of each row of a matrix

In [50]:
random_vector = np.random.rand(10, 5)
print(random_vector)
random_vector_2 = random_vector - random_vector.mean(axis=1, keepdims=True)
print(random_vector_2)

[[0.04677761 0.20578927 0.89699505 0.29324967 0.23346866]
 [0.2505574  0.75762463 0.35754894 0.02245057 0.94406413]
 [0.39297004 0.49562672 0.4507219  0.87826842 0.49697559]
 [0.62455426 0.66502254 0.77514137 0.23029203 0.88972191]
 [0.91202267 0.03086835 0.61177047 0.36618553 0.12820195]
 [0.11545339 0.34729351 0.2414404  0.27485631 0.67810783]
 [0.30509614 0.00222195 0.88144391 0.2172466  0.90247072]
 [0.75262983 0.64385402 0.64736512 0.29916102 0.44452239]
 [0.61913806 0.21026564 0.41623847 0.64352182 0.9592607 ]
 [0.35992953 0.41397434 0.90499667 0.69715577 0.59072478]]
[[-0.28847844 -0.12946678  0.561739   -0.04200638 -0.10178739]
 [-0.21589173  0.2911755  -0.1089002  -0.44399856  0.47761499]
 [-0.14994249 -0.04728582 -0.09219063  0.33535589 -0.04593695]
 [-0.01239216  0.02807612  0.13819494 -0.40665439  0.25277549]
 [ 0.50221288 -0.37894145  0.20196067 -0.04362426 -0.28160784]
 [-0.2159769   0.01586322 -0.08998989 -0.05657397  0.34667754]
 [-0.15659973 -0.45947392  0.41974805 -0.